### ISSUE TITLE
[Bug]: Channels Won't Save

### ISSUE THREAD

**Issue by CringyCraze** [chrisbenincasa/tunarr#554]
### Contact Details

jkcool10201@gmail.com

### What happened?

After setting up, I attempted to create a channel, but none of my properties would save. My settings saved, but there were no saved pop ups when clicking save on the channel tabs. If I went to a different tab my channel does not exist. As well my filler lists don't create after adding content.

### Version

0.1.0

### What browser did you experience the the problem on?

Chrome

### What operating system are you using?

Windows 11

**Comment by chrisbenincasa** [comment]
Any errors in the browser developer console or server logs?

**Comment by chrisbenincasa** [comment]
Looking into this

**Comment by chrisbenincasa** [comment]
We switched to a new routing framework on the dev branch recently and are working out some kinks

**Comment by chrisbenincasa** [comment]
Should be fixed in https://github.com/chrisbenincasa/tunarr/pull/555

**Comment by darth2499** [comment]
I'm still having issues where when I create a Filler Channel and add my media, after clicking Review it takes me to this page and no channel gets created.
![Screenshot 2024-06-22 at 17-02-57 Tunarr](https://github.com/chrisbenincasa/tunarr/assets/22630657/a0a0a35a-9394-4c82-b077-22a4f7951853)

**Comment by chrisbenincasa** [comment]
Ah sorry I neglected to look at the fillers. Can take a look

**Comment by chrisbenincasa** [comment]
This should be addressed in #560
